---
title: "ONLYBENEFITS"
author: "AranyaIyer"
date: "2023-03-30" #Last updated Feb 02, 2024
output: html_document
---
```{r}
library(tidyverse)
library(here)

# Specify paths to subfolders within current working directory
results <- here("analysis", "results","Dec042023") # where results to use are 
results_ben <- here("analysis", "results","Benefitonly","Feb022024") #where results to save should be  

# Read in and prep data
benefit <- read.csv(paste0(results, "/Estimates_avg_benefits.csv"))
baseline <- read.csv(paste0(results, "/Estimates_avg_baseline.csv"))

costfeas <- read.csv(paste0(results, "/CostFeas.csv"))
costfeas <- costfeas[-1,] # Remove baseline values
costfeas$Strategy <- as_factor(costfeas$Strategy)

#' ### Calculate the expected benefit (benefit x feasibility) for ALL, not just the best benefits 
# Tidy data
long <- gather(benefit, 
               key = Est.type, 
               value = Value, 
               colnames(benefit)[2]:colnames(benefit)[ncol(benefit)]) %>%
  separate(Est.type, c("Estimate", "Strategy"), sep = "[_]", remove = FALSE) %>%
  mutate(Strategy = as_factor(Strategy), 
         Ecological.Group = as_factor(Ecological.Group),
         Est.type = as_factor(Est.type)) 

# # Join with cost & feasibility table then weight benefit by feasibility -> AI: it changes between Avg. Feas and Min.Feas here - stick with avg. feas
joined <- left_join(long, costfeas, by = "Strategy") %>%
  mutate(Avg.ExpBen = Value * avg.Feas) 
# 
# # Reformat table and output results
exp.ben <- joined %>%
  select(c(Ecological.Group, Est.type, Avg.ExpBen)) %>% #AI: using only avg Feas here!
  spread(key = Est.type, value = Avg.ExpBen)

############################################################Doing this without feasibility multiplication. 
# joined <- left_join(long, costfeas, by = "Strategy")
# 
# exp.ben <- joined %>%
#   select(c(Ecological.Group, Est.type, Value)) %>% #AI: using NO feasibility here 
#   spread(key = Est.type, value = Value)

############################################################

write.csv(exp.ben, paste0(results_ben, "/ExpBenefits_Benefitsonly.csv"), row.names = FALSE)

#' Sample table:
#+ echo = FALSE
# knitr::kable(exp.ben, "simple")

# #' ### Calculate expected performance (baseline probability of persistence + expected benefits)
# # Join with baseline estimates to make sure the estimates line up correctly
# joined.base <- left_join(baseline, exp.ben, by = "Ecological.Group") 
# 
# # Add expected benefit estimates to (averaged) baseline and get the expected performance
# base.mat <- joined.base[,2:4]
# perf.mat <- joined.base[,5:ncol(joined.base)] + as.matrix(base.mat)
# 
# exp.perf <- cbind(joined.base$Ecological.Group,base.mat,perf.mat)
# names(exp.perf)[1] <- "Ecological.Group"
# 
# write.csv(exp.perf, paste0(results_ben, "/ExpPerform_all_Benefitsonly.csv"), row.names = FALSE)

#' Sample table:
#+ echo = FALSE
# knitr::kable(exp.perf, "simple")
```

```{r}

myPaths <- .libPaths()

myPaths <- c(myPaths, "C:/Users/aiyer/OneDrive - WORLD WILDLIFE FUND CANADA/Documents/ON PTM/PTM_3-point-est-main/analysis/code/packages")

.libPaths(myPaths)  # add new path

#NOW you Need to physically go to Packages > Project Library > Matrix 

library(Matrix)


library(consOpt)
library(tidyverse)
library(cowplot)
library(here)
library(ggplot2)
library(tidyr)
library(dplyr)
library(openxlsx)
library(stringr)
library(viridis)

PlotOptCurve <- function(summary.results, benefits.matrix, draw.labels=TRUE){
  
  tmp <- summary.results
  
  tmp$total_cost <- (tmp$total_cost / 10^6) # rescale x-axis to millions
  tmp$threshold <- round(tmp$threshold) # remove decimal points
  
  # Create plot object
  this.plot <- ggplot(tmp, aes(
    x = total_cost, 
    y = number_of_species, 
    group = threshold, 
    # linetype = factor(threshold),
    # shape = factor(threshold), 
    label = ifelse(strategies=="Baseline"," ",strategies)
  )
  ) +
    geom_step(aes(color = factor(threshold)), 
      # size = 0.8,
      # alpha = 0.6
    ) +
    geom_point(
      aes(color = factor(threshold)),
      size = 2
      ,show.legend = FALSE
    ) +
    theme_cowplot() +
    theme(legend.justification = c(1,0),
          legend.position = c(0.95, 0.05),
          legend.key.height = unit(0.6,"cm"),
          legend.key.width = unit(1, "cm"),
          legend.title = element_text(size = 12),
          legend.text = element_text(size = 12),
          plot.margin = margin(0.5, 1, 0.5, 0.5, "cm")
          # legend.title.align=0.5
    ) +scale_colour_manual(values = cols) +
    scale_y_continuous(
      # labels = function (x) floor(x), 
      breaks = min(tmp$number_of_species):length(benefits.matrix),
      limits = c(min(tmp$number_of_species), length(benefits.matrix))
    ) +
    labs(x = "Total cost (millions)", 
         y = "Number of groups benefitting"
         , color="Increase in Ben*Feas (%)"
         # , linetype = "Persistence\nthreshold (%)"
         , shape = "Increase in POP (%)"
    )
  
  if(draw.labels){
    this.plot <- this.plot + 
      geom_text_repel(size = 2
                      , hjust = "right"
                      # ,nudge_x = 0.5,
                      # nudge_y = -0.15
                      #,xlim = c(0, max(tmp$total_cost)+5),
                      # ylim = c(-0.5, max(tmp$number_of_species)+0.5),
                      # show.legend = FALSE
                      # # , direction = "both"
      )
  }
  
  plot(this.plot)
  this.plot
}


# Specify paths to subfolders within current working directory
input <- here("analysis", "data", "raw") # where raw data files are located
results <- here("analysis", "results","Dec042023") # where results of analysis should be saved
results_ben <- here("analysis", "results","Benefitonly","Feb022024") # where results of benefits analysis should be saved
figures <- here("analysis", "figures","Benefitonly","Feb022024") # where plots should be saved


combos <- read.csv(paste0(input, "/Combinations.csv"), header = TRUE) # list of individual strategies that make up each strategy (in columns). Should have a column for baseline and all strategies
exp.perf <- read.csv(paste0(results_ben, "/ExpBenefits_Benefitsonly.csv")) ##MIN or AVG feasibility was decided here 
costfeas <- read.csv(paste0(results, "/CostFeas.csv")) # estimated Cost and Feasibility for each Strategy (col 1), including Baseline
costs <- costfeas$Cost.0disc #changed here 
names(costs) <- costfeas$Strategy

##need to add baseline of zero here instead of OG baseline because then it is POP calcs and not Benefits calcs 
exp.perf$Wt.Best_Baseline <- 0 
exp.perf$Wt.Low_Baseline <- 0 
exp.perf$Wt.High_Baseline <- 0 
exp.perf <- exp.perf%>%select(Ecological.Group,Wt.Best_Baseline,Wt.Low_Baseline, Wt.High_Baseline, everything())

#' Create expected performance matrix for complementarity analysis (optimization)
perf.transposed <- exp.perf[,-1] %>%
  t() %>%
  data.frame() %>%
  setNames(exp.perf[,1]) %>%
  mutate(Est.type = rownames(.)) %>%
  separate(Est.type, c("Estimate", "Strategy"), sep = "[_]", remove = TRUE) %>%
  relocate(Estimate, Strategy) %>%
  remove_rownames()

best <- perf.transposed %>%
  filter(grepl("Best", Estimate)) %>%
  mutate(Estimate = NULL) %>%
  column_to_rownames("Strategy")

####rounding - justification: experts provided to whole numbers 
best <- round(best, digits=0)

write.csv(best, paste0(results_ben, "/ExpPerform_best_Benefitsonly.csv"), row.names = FALSE) 

##################################Fancy, yellow version prep
# best_clr <- round(best,digits=1)
# best_clr <- rownames_to_column(best_clr)
# names(best_clr)[1] <- "StrategyNumber"
# 
# strat_names <- read.csv(paste0(input, "/StrategyNames.csv"), header = TRUE) 
# best_clr <- merge(best_clr,strat_names, by="StrategyNumber")
# best_clr <- best_clr%>%select(StrategyName, StrategyNumber, everything())
# best_clr <- best_clr[-1,]
# best_clr$StrategyNumber <- str_sub(best_clr$StrategyNumber, 2)
# best_clr$StrategyNumber <- as.numeric(best_clr$StrategyNumber)
# best_clr <- best_clr %>% arrange(StrategyNumber)
# best_clr <- best_clr[,-2]
# names(best_clr)[1] <- "" # remove column name 
# write.xlsx(best_clr, paste0(results_ben, "/ExpPerform_best_Benefitsonly_format.xlsx"), rowNames = FALSE)
# 
# # Visualizing where the benefits lie -> I would say after 5%, 10%, 15%
# df_tidy <- gather(best, cols, value) 
# ben_densityplot <- ggplot(df_tidy, aes(x = value)) + 
#   geom_density(aes(color=cols))

#################################################

results.best <- Optimize(benefits.matrix = best, 
                    cost.vector = costs, 
                    combo.strategies = combos
                    , thresholds = c(10.00, 15.00) #can change thresholds here
                    )
write.csv(results.best, paste0(results_ben, "/Complementarity_best_Benefitsonly_10_15.csv"), row.names = FALSE)


cols <- c("5" = "goldenrod1", "10" = "darkmagenta","15" = "brown2","20" = "darkolivegreen3")

#' Plot using custom function above
optcurve.best <- PlotOptCurve(results.best, best, draw.labels = TRUE)

#+ eval = FALSE
ggsave(paste0(figures, "/Complementarity_best_Benefitsonly_10_15.pdf"), optcurve.best, width = 180, height = 120, units = "mm")


#' ### Uncertainty analysis by running the optimistic and pesimistic values 
#' Create expected performance matrices for lowest and highest estimates
low <- perf.transposed %>%
  filter(grepl("Low", Estimate)) %>%
  mutate(Estimate = NULL) %>%
  column_to_rownames("Strategy")

high <- perf.transposed %>%
  filter(grepl("High", Estimate)) %>%
  mutate(Estimate = NULL) %>%
  column_to_rownames("Strategy")

write.csv(low, paste0(results_ben, "/ExpPerform_low_Benefitsonly.csv"), row.names = FALSE) 
write.csv(high, paste0(results_ben, "/ExpPerform_high_Benefitsonly.csv"), row.names = FALSE) 

#' Run the optimization for the most pessimistic scenario (lowest estimates) 
#' and the most optimistic scenario (highest estimates)
#+ eval = FALSE
results.low <- Optimize(benefits.matrix = low,
                  cost.vector = costs,
                  combo.strategies = combos
                  , thresholds = c(10.01, 20.01)
                  )

results.high <- Optimize(benefits.matrix = high,
                  cost.vector = costs,
                  combo.strategies = combos
                  , thresholds = c(10.01, 20.01)
                  ) 

write.csv(results.low, paste0(results_ben, "/Complementarity_low_Benefitsonly.csv"), row.names = FALSE)
write.csv(results.high, paste0(results_ben, "/Complementarity_high_Benefitsonly.csv"), row.names = FALSE)


# OR using the custom plot function above:
optcurve.low <- PlotOptCurve(results.low, low, draw.labels = TRUE)
optcurve.high <- PlotOptCurve(results.high, high, draw.labels = TRUE)

# Save plots as pdf or tiff files
ggsave(paste0(figures, "/Complementarity_low_Benefitsonly.pdf"), optcurve.low, width = 180, height = 120, units = "mm")
ggsave(paste0(figures, "/Complementarity_high_Benefitsonly.pdf"), optcurve.high, width = 180, height = 120, units = "mm")


```

```{r}
#Saving all the right files to run the analysis 
library(openxlsx)

results_ben <- here("analysis", "results","Benefitonly","Apr192023_nofeas") # where results of analysis should be saved
exp.perf <- read.csv(paste0(results_ben, "/ExpBenefits_Benefitsonly.csv"))

best <- exp.perf %>% select(contains(c("Group","Best")))
high <- exp.perf %>% select(contains(c("Group","High")))
low <- exp.perf %>% select(contains(c("Group","Low")))

names(best) = gsub(pattern = "Wt.Best_", replacement = "", x = names(best))
names(high) = gsub(pattern = "Wt.High_", replacement = "", x = names(high))
names(low) = gsub(pattern = "Wt.Low_", replacement = "", x = names(low))


write.xlsx(best, paste0(results_ben, "/table2_best_ben.xlsx"), rowNames = FALSE)
write.xlsx(high, paste0(results_ben, "/table2_high_ben.xlsx"), rowNames = FALSE)
write.xlsx(low, paste0(results_ben, "/table2_low_ben.xlsx"), rowNames = FALSE)


```